# Generated by Django 5.1.4 on 2025-01-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_author_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
